---
- name: Create Docker container
  docker_container:
    name: spring-petclinic
    image: "{{ docker_image_name }}:{{ docker_image_version }}"
    state: started
    ports:
      - "80:8080"
  become: yes

